import cron from "node-cron";
import { getCurrentTrm, refreshCurrentTrm } from "./trm.service.js";
import { buildPlanSnapshot } from "../lib/planCaps.js";
import { db } from "@workspace/db";
import { postsTable, imageVariantsTable, publishLogTable, appSettingsTable, nichesTable, socialAccountsTable, subscriptionsTable, usersTable, musicTracksTable, businessesTable, plansTable, brandProfilesTable, contentHistoryTable, publishingSchedulesTable, landingPagesTable, mediaLibraryTable, passwordResetTokensTable } from "@workspace/db";
import { eq, and, lte, gte, isNotNull, isNull, lt, sql, or, inArray, not, ne } from "drizzle-orm";
import { publishToInstagram, publishReelToInstagram, resolveIgIdFromPageApi, maybeNotifyMetaAuthError } from "./instagram.service.js";
import { ObjectStorageService } from "../lib/objectStorage.js";
import { publishToTikTok } from "./tiktok.service.js";
import { publishToFacebook } from "./facebook.service.js";
import { generateBulkPosts, generateImagesForPostsBg, getBusinessSavedRefStyle, analyzeAndSuggestNiches } from "./ai.service.js";
import { resolveUserTimezone, startOfDayInTimezone } from "../lib/timezone.js";
import { runLearningExtraction, getWeeklyApprovalStats, getTopERNichesByUser } from "./learning.service.js";
import { decryptToken, encryptToken } from "../lib/tokenEncryption.js";
import { logger } from "../lib/logger.js";
import { auditLog, AuditAction } from "../lib/audit.js";
import { getCreditCosts, creditCostOf, reconcilePendingLedger } from "../lib/creditCosts.js";
import { notifyPostPublished, notifyPostFailed, notifyAutoGenerated, notifyNicheInsights, notifyMetaTokenAlert, notifyNoSocialAccount, getTelegramConfigForUser } from "./telegram.service.js";
import { seedMusicLibrary } from "@workspace/db/seed/music";

export const BOGOTA_TZ = "America/Bogota";

// Retry-first: posts fallidos se reintentan antes de liberar el espacio al generador.
// Un post ocupa el slot (status="scheduled") durante los reintentos.
// Solo pasa a "failed" al agotar todos los intentos, liberando entonces el espacio.
const MAX_PUBLISH_RETRIES = 3;        // intentos totales (1 original + 2 reintentos)
const RETRY_DELAY_MS      = 30 * 60 * 1000; // 30 min entre reintentos

// Optimal publishing windows for Cali, Colombia — ECO @eco.sas audience
// Segment: solar energy, homeowners + businesses, Cali UTC-5
//
// Research rationale (updated based on audience analysis, April 2026):
//
//   08:00 — B2B decision makers arrive at desk and check phone/social;
//           homeowners leaving for work, engaged and in "planning mode".
//           7am was too early — most Colombians are still in bed/breakfast
//           with low commercial intent at that hour.
//
//   12:00 — Colombian lunch break (12-2pm) is the universal peak engagement
//           slot: people scroll while eating, share content, save posts.
//           Strongest window across all segments.
//
//   18:00 — Post-work "golden scroll" hour in Cali: work ends 5-6pm,
//           people relax and browse social media before dinner.
//           7pm (19:00) coincides with dinner time in Cali (6:30-8pm)
//           and loses to family activity. 6pm catches them right as
//           they're winding down.
//
// Previously [7, 12, 19] — changed to [8, 12, 18] after audience analysis.
export const OPTIMAL_HOURS = [8, 12, 18];

// Colombia is permanently UTC-5 (no daylight saving time observed).
// All Bogotá-time conversions use this fixed offset.
export const BOGOTA_UTC_OFFSET_H = 5; // UTC-5

/**
 * Returns a plain object with { hour, day } in Bogotá local time for any UTC Date.
 * Uses UTC arithmetic — no locale/system-timezone dependency.
 */
function toBogotaTime(utcDate: Date): { hour: number; day: number; date: number } {
  const bogotaMs = utcDate.getTime() - BOGOTA_UTC_OFFSET_H * 3600 * 1000;
  const d = new Date(bogotaMs);
  return { hour: d.getUTCHours(), day: d.getUTCDay(), date: d.getUTCDate() };
}

function isInOptimalWindow(date: Date): boolean {
  const { hour } = toBogotaTime(date);
  // Optimal windows in Bogotá/Cali time: 08-10, 12-14, 18-20
  return (
    (hour >= 8  && hour < 10) ||
    (hour >= 12 && hour < 14) ||
    (hour >= 18 && hour < 20)
  );
}

/**
 * Returns the next UTC Date that falls on an OPTIMAL_HOURS slot in Bogotá time.
 * OPTIMAL_HOURS = [8, 12, 18] are Bogotá local hours.
 * UTC = Bogotá + 5, e.g. 8am Bogotá = 13:00 UTC, 12pm = 17:00 UTC, 6pm = 23:00 UTC.
 */
export function getNextOptimalSlot(from: Date = new Date()): Date {
  for (let dayOffset = 0; dayOffset <= 14; dayOffset++) {
    for (const bogotaHour of OPTIMAL_HOURS) {
      // Convert Bogotá hour → UTC hour (Colombia is always UTC-5, no DST)
      const utcHour = bogotaHour + BOGOTA_UTC_OFFSET_H;

      // Build a candidate UTC date anchored to the correct UTC day/hour
      const candidate = new Date(from);
      candidate.setUTCDate(from.getUTCDate() + dayOffset);
      candidate.setUTCHours(utcHour, 0, 0, 0);

      if (candidate <= from) continue;

      return candidate;
    }
  }

  // Safety fallback: 24h from now
  return new Date(from.getTime() + 24 * 3600 * 1000);
}

let schedulerStarted = false;

/**
 * Timestamp de la última FINALIZACIÓN de checkAndAutoGenerate() (éxito o error).
 * El gap filler consulta este valor para decidir si el auto-gen del día ya terminó.
 * Semántica de completion (no de inicio) → el gap filler puede leer los posts ya insertados.
 */
let lastAutoGenCompletedAt: Date | null = null;

export function startScheduler() {
  if (schedulerStarted) return;
  schedulerStarted = true;

  // Every 5 minutes: publish any scheduled posts whose time has arrived
  cron.schedule("*/5 * * * *", async () => {
    await publishScheduledPosts();
  }, { timezone: BOGOTA_TZ });

  // Daily at 06:00 Bogotá: check content levels and auto-generate if needed
  cron.schedule("0 6 * * *", async () => {
    await checkAndAutoGenerate();
  }, { timezone: BOGOTA_TZ });

  // At 10:00, 14:00, 18:00, 22:00 Bogotá: detect and fill empty days in next 48h.
  // Fixed slots guarantee no overlap with the 06:00 checkAndAutoGenerate.
  // An extra 1-hour guard (completion-based) prevents brief double-runs if the
  // server restarts mid-job or any edge-case causes early completion.
  cron.schedule("0 10,14,18,22 * * *", async () => {
    await checkDailyGapsAndFill();
  }, { timezone: BOGOTA_TZ });

  // Every 3 days at 07:00 Bogotá: sync engagement metrics for published IG posts
  cron.schedule("0 7 */3 * *", async () => {
    await syncPublishedPostMetrics();
  }, { timezone: BOGOTA_TZ });

  // 1st and 16th of each month at 08:30 Bogotá: refresh Instagram audience snapshot
  cron.schedule("30 8 1,16 * *", async () => {
    await refreshInstagramAudience();
  }, { timezone: BOGOTA_TZ });

  // Daily at 09:00 Bogotá: check if 15 calendar days have passed since last niche insights report
  cron.schedule("0 9 * * *", async () => {
    await maybeRunNicheInsightsReport();
  }, { timezone: BOGOTA_TZ });

  // Every day at 01:00 Bogotá: expire subscriptions past their periodEnd
  cron.schedule("0 1 * * *", async () => {
    await expireSubscriptions();
  }, { timezone: BOGOTA_TZ });

  // 1st of each month at 03:00 Bogotá: rotate music library (remove 10 unused, add 10 trending)
  cron.schedule("0 3 1 * *", async () => {
    await rotateMusicLibrary();
  }, { timezone: BOGOTA_TZ });

  // 1st of each month at 10:00 Bogotá: send monthly analytics email report to all paid users
  cron.schedule("0 10 1 * *", async () => {
    await sendMonthlyAnalyticsEmails();
  }, { timezone: BOGOTA_TZ });

  // Daily at 10:00 Bogotá: extract content learnings from top posts per segment + geo.
  // Runs after metrics sync window (07:00) so fresh engagement data is already in.
  // Internal freshness guard prevents re-processing users whose learnings are <20h old
  // with no new post activity (avoids unnecessary OpenAI calls on unchanged data).
  cron.schedule("0 10 * * *", async () => {
    logger.info("[LearningEngine] Starting daily learning extraction...");
    await runLearningExtraction();
    logger.info("[LearningEngine] Daily extraction complete.");
  }, { timezone: BOGOTA_TZ });

  // Weekly on Sunday at 09:00 Bogotá: send approval feedback summary via Telegram
  // to users who have signals in the past 7 days. Reports top approved/rejected niches
  // so users understand what content HazPost will prioritize. Non-blocking — any failure is silent.
  cron.schedule("0 9 * * 0", async () => {
    logger.info("[FeedbackReport] Starting weekly approval feedback summary...");
    try {
      const usersWithSignals = await db.execute(sql`
        SELECT DISTINCT user_id
        FROM niche_approval_signals
        WHERE created_at >= NOW() - INTERVAL '7 days'
      `);
      for (const row of usersWithSignals.rows) {
        const userId = (row as { user_id: number }).user_id;
        try {
          const config = await getTelegramConfigForUser(userId);
          if (!config) continue;
          const [{ mostApproved, mostRejected }, topER] = await Promise.all([
            getWeeklyApprovalStats(undefined, userId, 7),
            getTopERNichesByUser(userId, 30, 5),
          ]);
          if (mostApproved.length === 0 && mostRejected.length === 0 && topER.length === 0) continue;
          const lines: string[] = ["<b>📊 Resumen semanal de nichos — HazPost</b>\n"];
          if (mostApproved.length > 0) {
            lines.push("✅ <b>Más aprobados esta semana (aparecerán más):</b>");
            for (const { nicheName, count } of mostApproved) {
              lines.push(`  • ${nicheName} — ${count} aprobación${count !== 1 ? "es" : ""}`);
            }
          }
          if (mostRejected.length > 0) {
            lines.push("\n❌ <b>Más rechazados esta semana (aparecerán menos):</b>");
            for (const { nicheName, count } of mostRejected) {
              lines.push(`  • ${nicheName} — ${count} rechazo${count !== 1 ? "s" : ""}`);
            }
          }
          if (topER.length > 0) {
            lines.push("\n📈 <b>Nichos con mejor rendimiento publicado (últimos 30 días):</b>");
            for (const { nicheName, erPct, pubCount } of topER) {
              lines.push(`  • ${nicheName} — ER ${erPct}% (${pubCount} post${pubCount !== 1 ? "s" : ""})`);
            }
          }
          lines.push("\n<i>HazPost aprende de tus preferencias y resultados cada semana para mostrarte más de lo que funciona.</i>");
          const res = await fetch(`https://api.telegram.org/bot${config.botToken}/sendMessage`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ chat_id: config.chatId, text: lines.join("\n"), parse_mode: "HTML", disable_web_page_preview: true }),
          });
          if (!res.ok) logger.warn({ userId }, "[FeedbackReport] Telegram send failed");
        } catch (err) {
          logger.warn({ err, userId }, "[FeedbackReport] Failed to send report for user");
        }
      }
      logger.info("[FeedbackReport] Weekly summary complete.");
    } catch (err) {
      logger.warn({ err }, "[FeedbackReport] Weekly summary job failed");
    }
  }, { timezone: BOGOTA_TZ });

  // Daily at 08:00 Bogotá: force-refresh TRM cache so today's official rate is loaded
  // regardless of when the previous fetch occurred (bypasses 24h TTL).
  cron.schedule("0 8 * * *", async () => {
    const trm = await refreshCurrentTrm();
    logger.info(`[TRM] Daily refresh complete: ${trm} COP/USD`);
  }, { timezone: BOGOTA_TZ });

  // Daily at 11:00 Bogotá: check Meta token expiry — auto-renew if within 15 days
  cron.schedule("0 11 * * *", async () => {
    await checkAndRenewMetaToken();
  }, { timezone: BOGOTA_TZ });

  // Every hour: reconcile pending credit deductions older than 30 min — refund if AI generation crashed
  cron.schedule("0 * * * *", async () => {
    try {
      const refunded = await reconcilePendingLedger(30);
      if (refunded > 0) {
        logger.info({ refunded }, "[CreditLedger] Reconciliation: refunded stale pending deductions");
      }
    } catch (err) {
      logger.error({ err }, "[CreditLedger] Reconciliation job failed");
    }
  }, { timezone: BOGOTA_TZ });

  // Daily at 02:00 Bogotá: permanently purge users that have been in the trash for 30+ days
  cron.schedule("0 2 * * *", async () => {
    await purgeExpiredTrash();
  }, { timezone: BOGOTA_TZ });

  // On startup: pre-warm TRM cache so first billing request is instant
  getCurrentTrm().catch(err => logger.warn(`[TRM] Startup pre-warm failed: ${err}`));

  // On startup: if library is empty, auto-sync music from Pixabay
  setTimeout(() => { syncMusicIfEmpty(); }, 10_000);

  // On startup (after 30s): run learning extraction once so DB has fresh learnings immediately
  setTimeout(async () => {
    logger.info("[LearningEngine] Startup extraction triggered...");
    await runLearningExtraction();
    logger.info("[LearningEngine] Startup extraction done.");
  }, 30_000);

  logger.info("Scheduler started — publish check every 5 min, auto-generate at 06:00 Bogotá, gap-fill at 10/14/18/22h Bogotá (completion-guard), metrics sync every 3 days, audience refresh on 1st & 16th, niche insights every 15 days at 09:00, subscription expiry daily 01:00, music rotation 1st of month 03:00, learning extraction DAILY at 10:00 (freshness guard skips unchanged users), TRM pre-warm daily 08:00, Meta token renewal daily 11:00, trash purge daily 02:00");
}

/**
 * Permanently purges users that have been in the trash for 30+ days.
 * Runs daily at 02:00 Bogotá.
 */
async function purgeExpiredTrash(): Promise<void> {
  try {
    const cutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    const expired = await db.select({ id: usersTable.id, email: usersTable.email })
      .from(usersTable)
      .where(and(isNotNull(usersTable.deletedAt), lt(usersTable.deletedAt, cutoff)));

    if (expired.length === 0) return;

    logger.info({ count: expired.length }, "[Trash] Auto-purging expired trash users");

    for (const user of expired) {
      try {
        const userPosts = await db.select({ id: postsTable.id }).from(postsTable).where(eq(postsTable.userId, user.id));
        if (userPosts.length > 0) {
          const postIds = userPosts.map(p => p.id);
          await db.delete(imageVariantsTable).where(inArray(imageVariantsTable.postId, postIds)).catch(() => {});
          await db.delete(publishLogTable).where(inArray(publishLogTable.postId, postIds)).catch(() => {});
        }
        await db.delete(postsTable).where(eq(postsTable.userId, user.id)).catch(() => {});
        await db.delete(nichesTable).where(eq(nichesTable.userId, user.id)).catch(() => {});
        await db.delete(socialAccountsTable).where(eq(socialAccountsTable.userId, user.id)).catch(() => {});
        await db.delete(mediaLibraryTable).where(eq(mediaLibraryTable.userId, user.id)).catch(() => {});
        await db.delete(landingPagesTable).where(eq(landingPagesTable.userId, user.id)).catch(() => {});
        await db.delete(brandProfilesTable).where(eq(brandProfilesTable.userId, user.id)).catch(() => {});
        await db.delete(businessesTable).where(eq(businessesTable.userId, user.id)).catch(() => {});
        await db.delete(contentHistoryTable).where(eq(contentHistoryTable.userId, user.id)).catch(() => {});
        await db.delete(publishingSchedulesTable).where(eq(publishingSchedulesTable.userId, user.id)).catch(() => {});
        await db.delete(passwordResetTokensTable).where(eq(passwordResetTokensTable.userId, user.id)).catch(() => {});
        await db.delete(subscriptionsTable).where(eq(subscriptionsTable.userId, user.id)).catch(() => {});
        await db.delete(usersTable).where(eq(usersTable.id, user.id));
        logger.info({ userId: user.id, email: user.email }, "[Trash] User permanently purged after 30-day retention");
      } catch (err) {
        logger.error({ err, userId: user.id }, "[Trash] Failed to purge user");
      }
    }
  } catch (err) {
    logger.error({ err }, "[Trash] Auto-purge job failed");
  }
}

/**
 * Auto-generation job: checks settings and generates content if below threshold.
 * Called daily at 06:00 Bogotá.
 * Respects the configured generation frequency (weekly = 7 days, biweekly = 15, monthly = 30).
 */
async function checkAndAutoGenerate() {
  try {
    const settings = await db.select().from(appSettingsTable);
    const settingsMap: Record<string, string> = {};
    for (const s of settings) settingsMap[s.key] = s.value;

    const autoGenEnabled = settingsMap["auto_generation"] === "true";
    if (!autoGenEnabled) {
      logger.info("Auto-generation is disabled. Skipping.");
      return;
    }

    const platform = settingsMap["default_platform"] ?? "both";
    const now = new Date();

    // Iterate over every active business independently — each business gets its own
    // content pool with the correct userId and businessId for brand-accurate generation.
    // Per-business auto_generation_enabled and generation_frequency override global defaults.
    // GUARD: JOIN with users to exclude businesses of soft-deleted users (deleted_at IS NOT NULL).
    // Without this, deleting a user left their businesses active, causing N phantom image jobs.
    const activeBusinesses = await db
      .select({
        id: businessesTable.id,
        userId: businessesTable.userId,
        name: businessesTable.name,
        autoGenerationEnabled: businessesTable.autoGenerationEnabled,
        generationFrequency: businessesTable.generationFrequency,
        timezone: usersTable.timezone,
        brandCountry: usersTable.brandCountry,
      })
      .from(businessesTable)
      .innerJoin(usersTable, eq(usersTable.id, businessesTable.userId))
      .where(and(
        eq(businessesTable.isActive, true),
        isNull(usersTable.deletedAt),
      ));

    if (activeBusinesses.length === 0) {
      logger.warn("Auto-generation skipped: no active businesses found");
      return;
    }

    let totalGenerated = 0;
    let notifyDaysAhead = 15; // representative frequency for Telegram notification

    // Collect image job queues during the text-generation loop, then process them
    // sequentially AFTER the loop. This prevents OpenAI rate-limit bursts when many
    // businesses are active (e.g. test accounts): instead of N×4 concurrent DALL-E
    // calls, each business's image batch finishes before the next one starts.
    const pendingImageQueues: Array<{ bizId: number; bizName: string; jobs: Awaited<ReturnType<typeof generateBulkPosts>>["imageJobs"] }> = [];

    for (const biz of activeBusinesses) {
      const bizUserId: number | undefined = biz.userId ?? undefined;

      // ── SCHEDULER NULL OWNER GUARD ──────────────────────────────────────────
      // bizUserId is biz.userId coerced to undefined when null. A business with
      // no owner (null userId) must never generate posts — there is no tenant to
      // stamp on the rows and generateBulkPosts would silently skip the tenant
      // assertion (userId == null bypass). Fail fast here instead.
      if (bizUserId == null) {
        logger.warn({ bizId: biz.id, bizName: biz.name }, "[AutoGen] Skipping business with null userId — cannot generate without owner context");
        continue;
      }

      // Respect per-business auto-generation toggle — only generate if explicitly enabled
      if (!biz.autoGenerationEnabled) {
        logger.info(`Auto-generation disabled for biz ${biz.id} (${biz.name}) — skipping`);
        continue;
      }

      // Per-business frequency: '7' = weekly, '15' = biweekly (default), '30' = monthly
      const bizFreqDays = parseInt(biz.generationFrequency ?? "15", 10);
      const daysToGenerate = [7, 15, 30].includes(bizFreqDays) ? bizFreqDays : 15;
      const minPostsRequired = Math.max(3, Math.floor(daysToGenerate * 0.5));
      const lookahead = new Date(now.getTime() + daysToGenerate * 24 * 60 * 60 * 1000);

      try {
        // Count upcoming posts scoped to this specific business
        const upcomingForBiz = await db
          .select({ id: postsTable.id })
          .from(postsTable)
          .where(and(
            eq(postsTable.businessId, biz.id),
            gte(postsTable.scheduledAt, now),
            lte(postsTable.scheduledAt, lookahead)
          ));

        if (upcomingForBiz.length >= minPostsRequired) {
          logger.info(`Auto-generation skipped for biz ${biz.id} (${biz.name}): ${upcomingForBiz.length} posts already scheduled`);
          continue;
        }

        // Get active niches for this business only
        const bizNiches = await db
          .select({ id: nichesTable.id })
          .from(nichesTable)
          .where(and(eq(nichesTable.active, true), eq(nichesTable.businessId, biz.id)));

        if (bizNiches.length === 0) {
          logger.info(`Auto-generation skipped for biz ${biz.id} (${biz.name}): no active niches`);
          continue;
        }

        const autoContentTypes = ["image", "reel", "carousel", "story"];

        // ── Snapshot credit check — skip this business if user cannot afford even 1 post ──
        // Real atomicity is enforced per-post inside generateBulkPosts via
        // checkAndDeductCredits (SELECT FOR UPDATE in its own transaction) per post.
        // NOTE: bizUserId is guaranteed non-null here — the isolation guard above
        // already continues if bizUserId == null.
        const [schedCreditRow] = await db
          .select({ credits: subscriptionsTable.creditsRemaining })
          .from(subscriptionsTable)
          .where(eq(subscriptionsTable.userId, bizUserId))
          .limit(1);
        const schedCreditsHad = schedCreditRow?.credits ?? 0;
        const schedCosts = await getCreditCosts();
        const minCostForAnyPost = Math.min(...autoContentTypes.map(ct => creditCostOf(ct, schedCosts)));
        if (schedCreditsHad < minCostForAnyPost) {
          logger.info(`Auto-generation skipped for biz ${biz.id} (${biz.name}): user ${bizUserId} has ${schedCreditsHad} credits — needs at least ${minCostForAnyPost} for cheapest content type`);
          continue;
        }

        logger.info(`Auto-generating for biz ${biz.id} (${biz.name}): ${daysToGenerate} days (${upcomingForBiz.length} posts found, need ≥${minPostsRequired})`);

        const bizNicheIds = bizNiches.map(n => n.id);

        // Resolve saved reference image style BEFORE building image jobs
        const savedRefStyle = await getBusinessSavedRefStyle(biz.id, bizUserId).catch(() => "");

        let postIds: number[] = [];
        let imageJobs: Awaited<ReturnType<typeof generateBulkPosts>>["imageJobs"] = [];

        // ISOLATION: bizUserId = biz.userId (guaranteed by isolation guard above).
        // generateBulkPosts will further assert this inside its own tenant check.
        const userTimezone = resolveUserTimezone(biz);
        ({ postIds, imageJobs } = await generateBulkPosts(
          daysToGenerate, bizNicheIds, platform,
          autoContentTypes, undefined, undefined,
          true,       // isAutomatic — enables 10-day topic gap rule
          bizUserId,
          biz.id,
          undefined, // maxPosts: per-post atomic charge enforces the limit
          false,     // creditsPreReserved
          userTimezone,
        ));

        // Stamp saved ref style on every image job that has no explicit scene override.
        const stampedJobs = savedRefStyle
          ? imageJobs.map(j => (!j.imageScene && !j.batchRefStyle ? { ...j, batchRefStyle: savedRefStyle } : j))
          : imageJobs;

        // Queue image jobs to run sequentially after ALL text generation is done.
        // Do NOT fire here — collecting and processing after the loop prevents
        // concurrent DALL-E bursts (N businesses × 4 workers = N×4 parallel calls).
        if (stampedJobs.length > 0) {
          pendingImageQueues.push({ bizId: biz.id, bizName: biz.name, jobs: stampedJobs });
        }

        logger.info(`Auto-generation complete for biz ${biz.id} (${biz.name}): ${postIds.length} posts queued for text, ${stampedJobs.length} image jobs pending sequential processing${savedRefStyle ? " (with saved ref style)" : ""}`);
        totalGenerated += postIds.length;
        if (postIds.length > 0) notifyDaysAhead = daysToGenerate; // use last generating business's frequency
      } catch (bizErr) {
        logger.error(`Auto-generation failed for biz ${biz.id} (${biz.name}): ${bizErr}`);
      }
    }

    // ── Sequential image generation ─────────────────────────────────────────────
    // Process each business's image batch one at a time. This keeps total DALL-E
    // concurrency at the per-function cap (currently 4) instead of N×4 when N
    // businesses are active simultaneously. Safe to run in background since the
    // posts are already created and visible in the approval queue.
    if (pendingImageQueues.length > 0) {
      logger.info(`Auto-gen: starting sequential image processing for ${pendingImageQueues.length} business(es), ${pendingImageQueues.reduce((s, q) => s + q.jobs.length, 0)} total jobs`);
      void (async () => {
        for (const { bizId, bizName, jobs } of pendingImageQueues) {
          logger.info(`Auto-gen images: starting biz ${bizId} (${bizName}) — ${jobs.length} jobs`);
          await generateImagesForPostsBg(jobs).catch(e =>
            logger.error(`Auto-gen image jobs failed for biz ${bizId} (${bizName}): ${e}`)
          );
          logger.info(`Auto-gen images: finished biz ${bizId} (${bizName})`);
        }
        logger.info(`Auto-gen: all image queues processed`);
      })();
    }

    if (totalGenerated > 0) {
      notifyAutoGenerated(totalGenerated, notifyDaysAhead).catch(e =>
        logger.warn(`Telegram auto-generate notify failed: ${e}`)
      );
    }
  } catch (err) {
    logger.error(`Auto-generation failed: ${err}`);
  } finally {
    // Marcar como "completado" (éxito o error) para que checkDailyGapsAndFill
    // sepa que el auto-gen ya terminó y los posts ya están en DB.
    lastAutoGenCompletedAt = new Date();
  }
}

/**
 * Gap-fill job: runs every 2 hours and checks whether any of the next 2 calendar
 * days (in Bogotá time) has 0 posts scheduled for a business with auto-gen enabled.
 * If a gap is detected, generates 3 days of content to fill it and buffer ahead.
 *
 * Conservative by design — only fires when a day is completely empty.
 * Does not replace the 06:00 checkAndAutoGenerate; it is complementary.
 */
async function checkDailyGapsAndFill() {
  try {
    // ── Guard: no correr si checkAndAutoGenerate completó hace menos de 1 hora ──────────
    // Semántica de COMPLETION: el timestamp se setea cuando el auto-gen TERMINA (finally).
    // Si el auto-gen aún no terminó → lastAutoGenCompletedAt es null o del día anterior,
    // y el cron de 10:00+ garantiza que no hay solapamiento con el job de 06:00.
    // La ventana de 1h es un safety net extra para reinicios del servidor u edge cases.
    if (lastAutoGenCompletedAt) {
      const msSinceCompletion = Date.now() - lastAutoGenCompletedAt.getTime();
      const ONE_HOUR_MS = 3600 * 1000;
      if (msSinceCompletion < ONE_HOUR_MS) {
        logger.info(
          { msSinceCompletion, lastAutoGenCompletedAt },
          "[GapFill] Skipping — checkAndAutoGenerate completed less than 1 hour ago (completion guard)",
        );
        return;
      }
    }

    // Respect global auto_generation kill-switch
    const settings = await db.select().from(appSettingsTable);
    const settingsMap: Record<string, string> = {};
    for (const s of settings) settingsMap[s.key] = s.value;

    if (settingsMap["auto_generation"] !== "true") {
      logger.info("[GapFill] Auto-generation globally disabled — skipping gap check");
      return;
    }

    const platform = settingsMap["default_platform"] ?? "both";
    const now = new Date();

    // Los límites de día (mañana, pasado) se calculan POR NEGOCIO dentro del loop,
    // usando el timezone real del usuario en lugar de Bogotá hardcodeado.
    // Ver: startOfDayInTimezone() en lib/timezone.ts

    // Only iterate businesses that have auto-gen explicitly enabled in the DB query
    // GUARD: JOIN with users to exclude soft-deleted user businesses (same as 06:00 job)
    const activeBusinesses = await db
      .select({
        id: businessesTable.id,
        userId: businessesTable.userId,
        name: businessesTable.name,
        timezone: usersTable.timezone,
        brandCountry: usersTable.brandCountry,
      })
      .from(businessesTable)
      .innerJoin(usersTable, eq(usersTable.id, businessesTable.userId))
      .where(and(
        eq(businessesTable.isActive, true),
        eq(businessesTable.autoGenerationEnabled, true),
        isNull(usersTable.deletedAt),
      ));

    if (activeBusinesses.length === 0) return;

    const pendingImageQueues: Array<{
      bizId: number;
      bizName: string;
      jobs: Awaited<ReturnType<typeof generateBulkPosts>>["imageJobs"];
    }> = [];

    for (const biz of activeBusinesses) {
      const bizUserId: number | undefined = biz.userId ?? undefined;

      // SCHEDULER NULL OWNER GUARD — matches 06:00 job pattern exactly
      if (bizUserId == null) {
        logger.warn({ bizId: biz.id }, "[GapFill] Skipping business with null userId");
        continue;
      }

      try {
        // ── Límites de día en el timezone del usuario (no Bogotá hardcodeado) ─────
        // startOfDayInTimezone garantiza que posts programados a las 8 PM local
        // (= 1 AM UTC del día siguiente para Bogotá) sean correctamente detectados.
        const bizTz = resolveUserTimezone(biz);
        const todayStart  = startOfDayInTimezone(now, bizTz);
        // +25h como margen para cubrir cualquier cambio de DST (máx ±1h)
        const day1Start   = startOfDayInTimezone(new Date(todayStart.getTime() + 25 * 3_600_000), bizTz);
        const day2Start   = startOfDayInTimezone(new Date(day1Start.getTime()  + 25 * 3_600_000), bizTz);
        const day3Start   = startOfDayInTimezone(new Date(day2Start.getTime()  + 25 * 3_600_000), bizTz);

        // Count non-rejected posts for tomorrow.
        // Checks scheduledAt, scheduledAtInstagram, and scheduledAtTiktok so that
        // posts with platform="both" (which can have different dates per platform)
        // are correctly detected and don't trigger a false gap.
        const tomorrowPosts = await db
          .select({ id: postsTable.id })
          .from(postsTable)
          .where(and(
            eq(postsTable.businessId, biz.id),
            ne(postsTable.status, "rejected"),
            or(
              and(gte(postsTable.scheduledAt, day1Start), lt(postsTable.scheduledAt, day2Start)),
              and(isNotNull(postsTable.scheduledAtInstagram), gte(postsTable.scheduledAtInstagram, day1Start), lt(postsTable.scheduledAtInstagram, day2Start)),
              and(isNotNull(postsTable.scheduledAtTiktok), gte(postsTable.scheduledAtTiktok, day1Start), lt(postsTable.scheduledAtTiktok, day2Start)),
            ),
          ));

        // Count non-rejected posts for the day after tomorrow.
        const dayAfterPosts = await db
          .select({ id: postsTable.id })
          .from(postsTable)
          .where(and(
            eq(postsTable.businessId, biz.id),
            ne(postsTable.status, "rejected"),
            or(
              and(gte(postsTable.scheduledAt, day2Start), lt(postsTable.scheduledAt, day3Start)),
              and(isNotNull(postsTable.scheduledAtInstagram), gte(postsTable.scheduledAtInstagram, day2Start), lt(postsTable.scheduledAtInstagram, day3Start)),
              and(isNotNull(postsTable.scheduledAtTiktok), gte(postsTable.scheduledAtTiktok, day2Start), lt(postsTable.scheduledAtTiktok, day3Start)),
            ),
          ));

        const hasTomorrowGap = tomorrowPosts.length === 0;
        const hasDayAfterGap = dayAfterPosts.length === 0;

        if (!hasTomorrowGap && !hasDayAfterGap) continue; // no gap → skip

        logger.info(
          { bizId: biz.id, bizName: biz.name, hasTomorrowGap, hasDayAfterGap },
          "[GapFill] Gap detected in next 48h — triggering generation",
        );

        // ── Credit snapshot check (same pattern as 06:00 job) ──────────────────
        const autoContentTypes = ["image", "reel", "carousel", "story"];
        const [schedCreditRow] = await db
          .select({ credits: subscriptionsTable.creditsRemaining })
          .from(subscriptionsTable)
          .where(eq(subscriptionsTable.userId, bizUserId))
          .limit(1);
        const creditsHad = schedCreditRow?.credits ?? 0;
        const schedCosts = await getCreditCosts();
        const minCostForAnyPost = Math.min(...autoContentTypes.map(ct => creditCostOf(ct, schedCosts)));

        if (creditsHad < minCostForAnyPost) {
          logger.info(
            { bizId: biz.id, bizName: biz.name, creditsHad, minCostForAnyPost },
            "[GapFill] Skipping — insufficient credits",
          );
          continue;
        }

        // ── Niches check ────────────────────────────────────────────────────────
        const bizNiches = await db
          .select({ id: nichesTable.id })
          .from(nichesTable)
          .where(and(eq(nichesTable.active, true), eq(nichesTable.businessId, biz.id)));

        if (bizNiches.length === 0) {
          logger.info({ bizId: biz.id }, "[GapFill] Skipping — no active niches");
          continue;
        }

        const bizNicheIds = bizNiches.map(n => n.id);
        const savedRefStyle = await getBusinessSavedRefStyle(biz.id, bizUserId).catch(() => "");

        // Generate 3 days to fill the gap and provide a buffer ahead.
        // isAutomatic = true preserves the 10-day topic gap rule.
        const userTimezone = resolveUserTimezone(biz);
        const { postIds, imageJobs } = await generateBulkPosts(
          3, bizNicheIds, platform,
          autoContentTypes, undefined, undefined,
          true,       // isAutomatic
          bizUserId,
          biz.id,
          undefined,  // maxPosts: per-post atomic charge enforces the limit
          false,      // creditsPreReserved
          userTimezone,
        );

        const stampedJobs = savedRefStyle
          ? imageJobs.map(j => (!j.imageScene && !j.batchRefStyle ? { ...j, batchRefStyle: savedRefStyle } : j))
          : imageJobs;

        if (stampedJobs.length > 0) {
          pendingImageQueues.push({ bizId: biz.id, bizName: biz.name, jobs: stampedJobs });
        }

        logger.info(
          { bizId: biz.id, bizName: biz.name, postCount: postIds.length, imageJobCount: stampedJobs.length },
          "[GapFill] Generation queued",
        );
      } catch (bizErr) {
        logger.error({ err: bizErr, bizId: biz.id }, "[GapFill] Failed for business");
      }
    }

    // Sequential image processing — same pattern as 06:00 job to avoid DALL-E bursts
    if (pendingImageQueues.length > 0) {
      void (async () => {
        for (const { bizId, bizName, jobs } of pendingImageQueues) {
          logger.info({ bizId, bizName, jobCount: jobs.length }, "[GapFill] Starting image generation");
          await generateImagesForPostsBg(jobs).catch(e =>
            logger.error({ err: e, bizId }, "[GapFill] Image generation failed"),
          );
          logger.info({ bizId }, "[GapFill] Image generation done");
        }
      })();
    }
  } catch (err) {
    logger.error({ err }, "[GapFill] Job failed");
  }
}

/**
 * Syncs engagement metrics (likes, comments, reach, saves, shares) for all
 * published Instagram posts that have an instagramPostId stored.
 * Runs every 3 days at 07:00 Bogotá.
 * Uses the instagram_manage_insights permission.
 */
export async function syncPublishedPostMetrics(): Promise<{ synced: number; errors: number }> {
  const GRAPH = "https://graph.facebook.com/v22.0";
  let synced = 0;
  let errors = 0;
  try {
    // Iterate over ALL configured Instagram accounts (one per business) to sync
    // metrics for each business independently. This prevents cross-business
    // contamination where posts from business B would be synced using credentials
    // from business A just because they share the same userId.
    const igAccounts = await db
      .select()
      .from(socialAccountsTable)
      .where(eq(socialAccountsTable.platform, "instagram"));

    if (igAccounts.length === 0) {
      logger.warn("syncPublishedPostMetrics: no Instagram accounts configured");
      return { synced: 0, errors: 0 };
    }

    for (const igAccount of igAccounts) {
      if (!igAccount?.accessToken || !igAccount?.pageId) {
        logger.warn(`syncPublishedPostMetrics: account id=${igAccount.id} has no token or pageId — skipping`);
        continue;
      }
      const token = decryptToken(igAccount.accessToken);

      // Resolve Instagram Business/Creator Account ID from the Facebook Page.
      // Uses resolveIgIdFromPageApi which queries BOTH instagram_business_account
      // (Page Settings link) and connected_instagram_account (Account Center link).
      const igId = await resolveIgIdFromPageApi(igAccount.pageId!, token);
      if (!igId) {
        logger.warn(`syncPublishedPostMetrics: could not resolve IG Business Account ID for account ${igAccount.id} — no instagram_business_account or connected_instagram_account on page`);
        continue;
      }
      logger.info(`syncPublishedPostMetrics: resolved IG Business Account ID ${igId} for businessId=${igAccount.businessId}`);

      // Scope published posts to this specific business — never mix posts from different businesses
      const businessCond = igAccount.businessId != null
        ? and(eq(postsTable.status, "published"), isNotNull(postsTable.instagramPostId), eq(postsTable.businessId, igAccount.businessId))
        : and(eq(postsTable.status, "published"), isNotNull(postsTable.instagramPostId), eq(postsTable.userId, igAccount.userId!));

      const publishedPosts = await db
        .select({ id: postsTable.id, instagramPostId: postsTable.instagramPostId })
        .from(postsTable)
        .where(businessCond);

      logger.info(`syncPublishedPostMetrics: syncing ${publishedPosts.length} published IG posts for businessId=${igAccount.businessId}`);

      // Fetch all recent media from the IG Business Account with engagement fields.
      // We match by stored instagramPostId to avoid direct /mediaId queries
      // which return (#100) Missing Permission with Page Access Tokens.
      type IgMediaItem = { id: string; like_count?: number; comments_count?: number; timestamp?: string };
      const mediaMap = new Map<string, IgMediaItem>();
      let mediaNextPage: string | null = `${GRAPH}/${igId}/media?fields=id,like_count,comments_count,timestamp&limit=50&access_token=${token}`;

      while (mediaNextPage) {
        const mediaRes = await fetch(mediaNextPage);
        const mediaBody = await mediaRes.json() as {
          data?: IgMediaItem[];
          paging?: { next?: string };
          error?: { message: string };
        };
        if (mediaBody.error) {
          logger.warn(`syncPublishedPostMetrics: error listing IG media for account ${igAccount.id}: ${mediaBody.error.message}`);
          break;
        }
        for (const m of mediaBody.data ?? []) {
          mediaMap.set(m.id, m);
        }
        mediaNextPage = mediaBody.paging?.next ?? null;
        // Safety: stop after 5 pages (250 posts) to avoid runaway loops
        if (mediaMap.size >= 250) break;
      }

      logger.info(`syncPublishedPostMetrics: fetched ${mediaMap.size} IG media items from account ${igAccount.id}`);

      for (const post of publishedPosts) {
        try {
          const basic = mediaMap.get(post.instagramPostId!);
          if (!basic) {
            logger.warn(`syncPublishedPostMetrics: media ${post.instagramPostId} not found in IG account ${igId}`);
            errors++;
            continue;
          }

          // Insights endpoint for reach and saved (impressions removed — not supported in API v22+)
          const insightsRes = await fetch(
            `${GRAPH}/${post.instagramPostId}/insights?metric=reach,saved&access_token=${token}`
          );
          const insightsBody = await insightsRes.json() as {
            data?: { name: string; values: { value: number }[] }[];
            error?: { message: string };
          };
          const insightMap: Record<string, number> = {};
          if (!insightsBody.error && insightsBody.data) {
            for (const metric of insightsBody.data) {
              insightMap[metric.name] = metric.values?.[0]?.value ?? 0;
            }
          }
          if (insightsBody.error) {
            logger.warn(`syncPublishedPostMetrics: insights error for ${post.instagramPostId}: ${insightsBody.error.message}`);
          }

          await db.update(postsTable).set({
            ...(basic.like_count     != null && { likes:    basic.like_count }),
            ...(basic.comments_count != null && { comments: basic.comments_count }),
            ...(insightMap.reach     != null && { reach:    insightMap.reach }),
            ...(insightMap.saved     != null && { saves:    insightMap.saved }),
            updatedAt: new Date(),
          }).where(eq(postsTable.id, post.id));
          synced++;
        } catch (postErr) {
          logger.error(`syncPublishedPostMetrics: error for post #${post.id}: ${postErr}`);
          errors++;
        }
      }
    }
    logger.info(`syncPublishedPostMetrics: done — ${synced} synced, ${errors} errors`);
  } catch (err) {
    logger.error(`syncPublishedPostMetrics failed: ${err}`);
  }
  return { synced, errors };
}

/**
 * Fetches Instagram audience data (followers, online hours, demographics) and
 * stores a snapshot in app_settings as JSON (key = audience_snapshot).
 * Also stores a ISO timestamp in audience_snapshot_refreshed_at.
 * Runs on the 1st and 16th of each month at 08:30 Bogotá.
 */
export async function refreshInstagramAudience(): Promise<void> {
  const GRAPH = "https://graph.facebook.com/v22.0";
  try {
    // Fetch audience data for all configured Instagram accounts.
    // Snapshots are stored per-businessId key in app_settings.
    // Each account's audience data is stored independently to prevent cross-business contamination.
    const igAccounts = await db
      .select()
      .from(socialAccountsTable)
      .where(eq(socialAccountsTable.platform, "instagram"));

    if (igAccounts.length === 0) {
      logger.warn("refreshInstagramAudience: no Instagram accounts configured");
      return;
    }

    // Process each account independently
    for (const igAccount of igAccounts) {
      await refreshInstagramAudienceForAccount(igAccount, GRAPH);
    }
  } catch (err) {
    logger.error(`refreshInstagramAudience failed: ${err}`);
  }
}

async function refreshInstagramAudienceForAccount(
  igAccount: typeof socialAccountsTable.$inferSelect,
  GRAPH: string
): Promise<void> {
  try {
    if (!igAccount?.accessToken || !igAccount?.pageId) {
      logger.warn(`refreshInstagramAudience: account id=${igAccount.id} has no token or pageId — skipping`);
      return;
    }
    const token = decryptToken(igAccount.accessToken);
    const pageId = igAccount.pageId;
    // Audience snapshot key: scoped per business to prevent cross-business data overwrite.
    // Falls back to "audience_snapshot" only when businessId is not set (legacy accounts).
    // The analytics route reads using the same business-scoped key.
    const snapshotKey = igAccount.businessId != null
      ? `audience_snapshot_biz_${igAccount.businessId}`
      : "audience_snapshot";

    // Resolve IG Business/Creator Account ID — queries both instagram_business_account
    // and connected_instagram_account so Account Center-linked accounts are detected.
    const igId = await resolveIgIdFromPageApi(pageId, token);
    if (!igId) {
      logger.error(`refreshInstagramAudience: could not resolve IG Business ID for account ${igAccount.id}: no IG account linked to page`);
      return;
    }

    // Account info + followers
    const infoRes = await fetch(`${GRAPH}/${igId}?fields=username,followers_count,media_count&access_token=${token}`);
    const info = await infoRes.json() as { username?: string; followers_count?: number; media_count?: number };

    // Online followers by hour (when are followers online?)
    const onlineRes = await fetch(`${GRAPH}/${igId}/insights?metric=online_followers&period=lifetime&access_token=${token}`);
    const onlineData = await onlineRes.json() as { data?: unknown[]; error?: { message: string } };

    // Audience demographics
    const audienceRes = await fetch(
      `${GRAPH}/${igId}/insights?metric=audience_gender_age,audience_country,audience_city&period=lifetime&access_token=${token}`
    );
    const audienceData = await audienceRes.json() as { data?: unknown[]; error?: { message: string } };

    const snapshot = {
      refreshedAt: new Date().toISOString(),
      account: info,
      igBusinessId: igId,
      onlineFollowers: onlineData.data ?? null,
      onlineFollowersError: onlineData.error?.message ?? null,
      audience: audienceData.data ?? null,
      audienceError: audienceData.error?.message ?? null,
    };

    // Upsert into app_settings (keyed per business to avoid overwriting data from another business)
    const existing = await db.select().from(appSettingsTable).where(eq(appSettingsTable.key, snapshotKey));
    if (existing.length > 0) {
      await db.update(appSettingsTable).set({ value: JSON.stringify(snapshot), updatedAt: new Date() })
        .where(eq(appSettingsTable.key, snapshotKey));
    } else {
      await db.insert(appSettingsTable).values({ key: snapshotKey, value: JSON.stringify(snapshot) });
    }

    logger.info(`refreshInstagramAudience: snapshot saved for businessId=${igAccount.businessId} — ${info.followers_count} followers, igId=${igId}`);
  } catch (err) {
    logger.error(`refreshInstagramAudienceForAccount (account=${igAccount.id}) failed: ${err}`);
  }
}

/**
 * Batch-fetches emailVerified status for a set of userIds.
 * Returns a Set of userIds whose email IS verified.
 * Used by publishScheduledPosts to skip unverified users' posts (hard enforcement).
 */
async function getVerifiedUserIds(userIds: number[]): Promise<Set<number>> {
  if (userIds.length === 0) return new Set();
  const rows = await db
    .select({ id: usersTable.id, emailVerified: usersTable.emailVerified, role: usersTable.role })
    .from(usersTable)
    .where(inArray(usersTable.id, userIds));
  // Admins are always allowed; non-admins need emailVerified = true
  return new Set(rows.filter(u => u.role === "admin" || u.emailVerified === true).map(u => u.id));
}

async function publishScheduledPosts() {
  const now = new Date();

  // ── 1. Posts using the classic single scheduledAt (no per-platform dates) ──
  const scheduledPosts = await db
    .select()
    .from(postsTable)
    .where(
      and(
        eq(postsTable.status, "scheduled"),
        lte(postsTable.scheduledAt, now),
        // Only pick up posts that do NOT have per-platform dates set;
        // those are handled separately below.
        sql`${postsTable.scheduledAtInstagram} IS NULL`,
        sql`${postsTable.scheduledAtTiktok} IS NULL`,
      )
    );

  const unifiedUserIds = [...new Set(scheduledPosts.map(p => p.userId).filter((id): id is number => id != null))];
  const verifiedUnified = await getVerifiedUserIds(unifiedUserIds);

  for (const post of scheduledPosts) {
    if (post.userId != null && !verifiedUnified.has(post.userId)) {
      logger.warn(`[scheduler] skipping post #${post.id} — owner userId=${post.userId} has not verified email`);
      continue;
    }
    logger.info(`[scheduler] publishing post #${post.id} (unified schedule)`);
    await publishPost(post.id);
  }

  // ── 2. Per-platform: Instagram leg that has come due ────────────────────────
  const igDue = await db
    .select()
    .from(postsTable)
    .where(
      and(
        eq(postsTable.status, "scheduled"),
        lte(postsTable.scheduledAtInstagram, now),
        sql`${postsTable.instagramPostId} IS NULL`,
        sql`${postsTable.platform} IN ('instagram','both')`,
        // Retry-first: permite hasta MAX_PUBLISH_RETRIES intentos antes de bloquear el slot.
        sql`(SELECT COUNT(*) FROM publish_log WHERE post_id = ${postsTable.id} AND platform = 'instagram' AND status = 'failed') < ${MAX_PUBLISH_RETRIES}`,
      )
    );

  const igUserIds = [...new Set(igDue.map(p => p.userId).filter((id): id is number => id != null))];
  const verifiedIg = await getVerifiedUserIds(igUserIds);

  for (const post of igDue) {
    if (post.userId != null && !verifiedIg.has(post.userId)) {
      logger.warn(`[scheduler] skipping post #${post.id} → Instagram — owner userId=${post.userId} has not verified email`);
      continue;
    }
    logger.info(`[scheduler] publishing post #${post.id} → Instagram (per-platform)`);
    await publishPost(post.id, "instagram");
  }

  // ── 3. Per-platform: TikTok leg that has come due ───────────────────────────
  const tkDue = await db
    .select()
    .from(postsTable)
    .where(
      and(
        eq(postsTable.status, "scheduled"),
        lte(postsTable.scheduledAtTiktok, now),
        sql`${postsTable.tiktokPostId} IS NULL`,
        sql`${postsTable.platform} IN ('tiktok','both')`,
        // Retry-first: permite hasta MAX_PUBLISH_RETRIES intentos antes de bloquear el slot.
        sql`(SELECT COUNT(*) FROM publish_log WHERE post_id = ${postsTable.id} AND platform = 'tiktok' AND status = 'failed') < ${MAX_PUBLISH_RETRIES}`,
      )
    );

  const tkUserIds = [...new Set(tkDue.map(p => p.userId).filter((id): id is number => id != null))];
  const verifiedTk = await getVerifiedUserIds(tkUserIds);

  for (const post of tkDue) {
    if (post.userId != null && !verifiedTk.has(post.userId)) {
      logger.warn(`[scheduler] skipping post #${post.id} → TikTok — owner userId=${post.userId} has not verified email`);
      continue;
    }
    logger.info(`[scheduler] publishing post #${post.id} → TikTok (per-platform)`);
    await publishPost(post.id, "tiktok");
  }
}

/**
 * Publishes a single post.
 * @param platformOverride - When set, only publishes to that specific platform leg
 *   instead of all platforms associated with the post. Used for per-platform scheduling
 *   where Instagram and TikTok have independent scheduled times.
 */
export async function publishPost(postId: number, platformOverride?: "instagram" | "tiktok"): Promise<void> {
  const [post] = await db.select().from(postsTable).where(eq(postsTable.id, postId));
  if (!post) return;

  // Guard: si el negocio del post no tiene ninguna cuenta social ACTIVA y conectada,
  // fallar inmediatamente sin intentar publicar. Evita que el scheduler
  // intente publicar en ciclos repetidos para negocios sin cuentas.
  // Se filtra por connected='true' para ignorar filas stale/desconectadas.
  if (post.businessId != null) {
    const [hasSocialAccount] = await db
      .select({ id: socialAccountsTable.id })
      .from(socialAccountsTable)
      .where(
        and(
          eq(socialAccountsTable.businessId, post.businessId),
          eq(socialAccountsTable.connected, "true"),
        )
      )
      .limit(1);

    if (!hasSocialAccount) {
      const [biz] = await db
        .select({ name: businessesTable.name })
        .from(businessesTable)
        .where(eq(businessesTable.id, post.businessId))
        .limit(1);
      const bizName = biz?.name ?? `negocio #${post.businessId}`;
      const errorMsg = `El negocio "${bizName}" no tiene cuentas de redes sociales conectadas — conecta Instagram o TikTok en Configuración`;
      logger.warn(`[publishPost] Post #${postId} abortado: ${errorMsg}`);
      await db.insert(publishLogTable).values({
        postId: post.id,
        userId: post.userId ?? undefined,
        platform: post.platform ?? "instagram",
        status: "failed",
        errorMessage: errorMsg,
      });
      await db.update(postsTable)
        .set({ status: "failed" })
        .where(eq(postsTable.id, postId));
      notifyNoSocialAccount(
        post.id,
        post.postNumber ?? undefined,
        bizName,
        post.businessId,
        post.userId ?? undefined,
      ).catch(e => logger.error(`[Telegram] notifyNoSocialAccount error: ${e}`));
      return;
    }
  }

  const variants = await db
    .select()
    .from(imageVariantsTable)
    .where(eq(imageVariantsTable.postId, postId))
    .orderBy(imageVariantsTable.variantIndex);

  // selectedImageVariant stores the variant's DB id (not array index)
  const selectedVariant = variants.find(v => v.id === post.selectedImageVariant) || variants[0];
  const imageData = selectedVariant?.imageData ?? "";
  // For reel posts, the generated video may be stored on any variant (always the first by id).
  // Never restrict to selectedVariant only — scan all variants so the video is always found.
  const reelObjectPath = post.contentType === "reel"
    ? variants.find(v => v.reelObjectPath)?.reelObjectPath ?? null
    : selectedVariant?.reelObjectPath ?? null;
  // TikTok uses 9:16 variant if available (generated on approval for "both" portrait posts)
  const tiktokImageData = selectedVariant?.tiktokImageData ?? imageData;

  // For carousel posts with multiple slides, collect all images in order.
  // Filter out null/empty slides to avoid sending empty buffers to Instagram
  // (which triggers "Only photo or video can be accepted as media type").
  const isCarousel = post.contentType === "carousel" && variants.length > 1;
  const carouselImages = isCarousel
    ? (variants.map(v => v.imageData).filter(Boolean) as string[])
    : undefined;
  const tiktokCarouselImages = isCarousel
    ? (variants.map(v => v.tiktokImageData ?? v.imageData).filter(Boolean) as string[])
    : undefined;

  // Build final caption: apply niche custom text (before or after) if configured
  let finalCaption = post.caption;
  if (post.nicheId) {
    const [niche] = await db.select({
      customText: nichesTable.customText,
      customTextPosition: nichesTable.customTextPosition,
    }).from(nichesTable).where(eq(nichesTable.id, post.nicheId));
    const customText = niche?.customText?.trim() ?? "";
    if (customText) {
      const position = niche?.customTextPosition ?? "after";
      finalCaption = position === "before"
        ? `${customText}\n\n${post.caption}`
        : `${post.caption}\n\n${customText}`;
    }
  }

  logger.info(`Publishing post #${postId} — type=${post.contentType} slides=${variants.length} carousel=${isCarousel}${platformOverride ? ` [override=${platformOverride}]` : ''}`);

  // Platform resolution (see skill: publicacion-plataformas):
  //   "both"      → IG + TK + FB
  //   "instagram" → IG + FB  (excludes FB if already published — prevents retry duplicates)
  //   "tiktok"    → TK only
  let platforms: string[];
  if (platformOverride === "instagram") {
    const [fbPublished] = await db
      .select({ id: publishLogTable.id })
      .from(publishLogTable)
      .where(
        and(
          eq(publishLogTable.postId, postId),
          eq(publishLogTable.platform, "facebook"),
          eq(publishLogTable.status, "published"),
        ),
      );
    platforms = fbPublished ? ["instagram"] : ["instagram", "facebook"];
  } else if (platformOverride === "tiktok") {
    platforms = ["tiktok"];
  } else {
    platforms = post.platform === "both"
      ? ["instagram", "tiktok", "facebook"]
      : post.platform === "instagram"
      ? ["instagram", "facebook"]
      : [post.platform ?? "instagram"];
  }
  // ── True fail-closed isolation guard (last shield before Meta API) ───────────
  // 1. Null businessId → fail-closed: cannot determine which account to use.
  // 2. No active IG account for this (userId, businessId) pair → fail-closed.
  // 3. ig_user_id must be present — proves Instagram is actually linked to the page.
  // 4. VM-3 contamination check: page_id OR ig_user_id must be unique to this business.
  //    Catches the production case where HazPost biz=2 shares page_id/ig_user_id with ECO biz=1.
  // All checks use direct DB queries independent of getInstagramAccount filter logic.
  if (platforms.includes("instagram") && post.userId != null) {
    // ── Step 1: null businessId is unpublishable — no isolation possible ──────
    if (post.businessId == null) {
      const isolationErr = `[ISOLATION_GUARD] post #${postId} tiene businessId=null — imposible verificar propiedad de cuenta Instagram. Publicación cancelada para prevenir contaminación cross-business.`;
      logger.error({ postId: post.id, userId: post.userId }, isolationErr);
      await db.insert(publishLogTable).values({ postId: post.id, userId: post.userId ?? undefined, platform: "instagram", status: "failed", errorMessage: isolationErr });
      await db.update(postsTable).set({ status: "failed" }).where(eq(postsTable.id, postId));
      return;
    }

    // ── Step 2: Fetch the exact account for this (userId, businessId) ─────────
    const [thisAccount] = await db
      .select({ id: socialAccountsTable.id, businessId: socialAccountsTable.businessId, pageId: socialAccountsTable.pageId, igUserId: socialAccountsTable.igUserId })
      .from(socialAccountsTable)
      .where(and(
        eq(socialAccountsTable.userId, post.userId),
        eq(socialAccountsTable.businessId, post.businessId),
        eq(socialAccountsTable.platform, "instagram"),
        eq(socialAccountsTable.connected, "true"),
      ))
      .limit(1);

    if (!thisAccount) {
      const isolationErr = `[ISOLATION_GUARD] No se encontró cuenta Instagram activa para userId=${post.userId} businessId=${post.businessId}. Publicación cancelada.`;
      logger.error({ postId: post.id, userId: post.userId, businessId: post.businessId }, isolationErr);
      await db.insert(publishLogTable).values({ postId: post.id, userId: post.userId ?? undefined, platform: "instagram", status: "failed", errorMessage: isolationErr });
      await db.update(postsTable).set({ status: "failed" }).where(eq(postsTable.id, postId));
      return;
    }

    // ── Step 3: ig_user_id ausente — advertencia pero NO bloquea ────────────────
    // ECO publicó exitosamente 7 veces con ig_user_id=NULL porque publishToInstagram
    // lo obtiene en vivo desde la API de Meta usando el page access_token. Bloquear
    // aquí crea falsos positivos para cuentas legítimas configuradas antes de que
    // se añadiera ig_user_id al esquema. Solo logueamos para visibilidad.
    if (!thisAccount.igUserId) {
      logger.warn({ postId: post.id, saId: thisAccount.id, businessId: post.businessId },
        `[ISOLATION_GUARD] sa_id=${thisAccount.id} (biz=${post.businessId}) tiene ig_user_id=null — ` +
        "se obtendrá en vivo desde Meta API durante la publicación."
      );
    }

    // ── Step 4: VM-3 contamination — page_id debe ser único por negocio ─────────
    // Solo chequea page_id (no ig_user_id) porque ig_user_id puede ser NULL en
    // cuentas legítimas y NULL=NULL en SQL es UNKNOWN (no genera falsos positivos,
    // pero la intención del guard es clara con page_id solamente).
    const [conflictAccount] = await db
      .select({ id: socialAccountsTable.id, businessId: socialAccountsTable.businessId })
      .from(socialAccountsTable)
      .where(and(
        eq(socialAccountsTable.userId, post.userId),
        eq(socialAccountsTable.platform, "instagram"),
        ne(socialAccountsTable.businessId, post.businessId),
        thisAccount.pageId ? eq(socialAccountsTable.pageId, thisAccount.pageId) : sql`false`,
      ))
      .limit(1);

    if (conflictAccount) {
      const isolationErr = `[ISOLATION_GUARD] Contaminación VM-3: sa_id=${thisAccount.id} (biz=${post.businessId}) comparte page_id/ig_user_id con sa_id=${conflictAccount.id} (biz=${conflictAccount.businessId}). Publicación cancelada.`;
      logger.error({ postId: post.id, saId: thisAccount.id, conflictSaId: conflictAccount.id, pageId: thisAccount.pageId, igUserId: thisAccount.igUserId }, isolationErr);
      await db.insert(publishLogTable).values({ postId: post.id, userId: post.userId ?? undefined, platform: "instagram", status: "failed", errorMessage: isolationErr });
      await db.update(postsTable).set({ status: "failed" }).where(eq(postsTable.id, postId));
      return;
    }
  }

  let anySuccess = false;
  let igSuccess = false;
  let igPostUrl: string | null = null;

  for (const platform of platforms) {
    let result: { postId: string | null; postUrl: string | null; error: string | null };

    logger.info(`Publishing post #${postId} to ${platform}`);

    if (platform === "instagram") {
      // ── Reel with video: use Instagram Reels API ──────────────────────────────
      if (post.contentType === "reel" && reelObjectPath) {
        try {
          const storage = new ObjectStorageService();
          const videoUrl = await storage.getObjectEntityGetURL(reelObjectPath, 3600);
          result = await publishReelToInstagram(videoUrl, finalCaption, post.hashtags, post.userId, post.businessId);
        } catch (reelErr) {
          logger.warn(`Reel video URL generation failed for post #${postId}, falling back to image: ${reelErr}`);
          result = await publishToInstagram(imageData, finalCaption, post.hashtags, carouselImages, post.locationId, post.userId, post.contentType, post.businessId);
        }
      } else {
        result = await publishToInstagram(imageData, finalCaption, post.hashtags, carouselImages, post.locationId, post.userId, post.contentType, post.businessId);
      }
      if (!result.error) {
        igSuccess = true;
        igPostUrl = result.postUrl;
      } else {
        // Alert user (once per 24h) if Meta rejected the token — action required to reconnect
        maybeNotifyMetaAuthError(post.userId, postId, result.error).catch(() => {});
      }
    } else if (platform === "facebook") {
      result = await publishToFacebook(imageData, finalCaption, post.hashtags, carouselImages, post.locationId, post.userId, post.businessId);
      // If Facebook returns SKIP (no pages_manage_posts) but Instagram succeeded,
      // mark as cross-posted via Instagram instead of skipped.
      if (result.error?.startsWith("SKIP:") && igSuccess) {
        result = {
          postId: null,
          postUrl: igPostUrl,
          error: null,
        };
        await db.insert(publishLogTable).values({
          postId: post.id,
          userId: post.userId ?? undefined,
          platform,
          status: "crossposted",
          postUrl: igPostUrl,
          errorMessage: "Publicado vía cross-posting de Instagram — activa Share to Facebook en tu cuenta de Instagram",
        });
        anySuccess = true;
        logger.info(`Cross-posted post #${postId} to Facebook via Instagram`);
        continue;
      }
    } else {
      result = await publishToTikTok(tiktokImageData, finalCaption, post.hashtagsTiktok || post.hashtags, tiktokCarouselImages, post.userId, post.businessId);
    }

    const isSkipped = result.error?.startsWith("SKIP:");
    await db.insert(publishLogTable).values({
      postId: post.id,
      userId: post.userId ?? undefined,
      platform,
      status: result.error ? (isSkipped ? "skipped" : "failed") : "published",
      postUrl: result.postUrl,
      errorMessage: result.error,
    });

    if (!result.error) {
      anySuccess = true;
      if (platform === "instagram" && result.postId) {
        await db.update(postsTable).set({ instagramPostId: result.postId }).where(eq(postsTable.id, postId));
      }
      if (platform === "tiktok" && result.postId) {
        await db.update(postsTable).set({ tiktokPostId: result.postId }).where(eq(postsTable.id, postId));
      }
    } else if (!isSkipped) {
      logger.error(`Failed to publish post #${postId} to ${platform}: ${result.error}`);
    } else {
      logger.info(`Skipped publishing post #${postId} to ${platform}: ${result.error}`);
    }
  }

  // Retry-first: Posts que fallan se reintentan MAX_PUBLISH_RETRIES veces antes de marcarse
  // como "failed". Durante los reintentos mantienen status="scheduled", ocupando el slot
  // del calendario. Solo pasan a "failed" al agotar reintentos, liberando el espacio a la IA.
  //
  // Fallas permanentes (no social account, isolation guard) ya retornaron antes de este punto.
  // Cualquier falla que llega aquí es transitoria (API error, rate limit, timeout) → apta para retry.
  const currentRetries = post.publishRetries ?? 0;
  let finalStatus: string;
  let isRetrying = false;

  if (platformOverride && post.platform === "both") {
    if (anySuccess) {
      // Check if the other platform is already "done" (succeeded OR has a failure log)
      const [refreshed] = await db.select({
        instagramPostId: postsTable.instagramPostId,
        tiktokPostId: postsTable.tiktokPostId,
      }).from(postsTable).where(eq(postsTable.id, postId));

      const bothSucceeded = !!(refreshed?.instagramPostId && refreshed?.tiktokPostId);
      if (bothSucceeded) {
        finalStatus = "published";
      } else {
        // Check if the other platform already has a failure logged
        const otherPlatform = platformOverride === "instagram" ? "tiktok" : "instagram";
        const [otherFailed] = await db
          .select({ id: publishLogTable.id })
          .from(publishLogTable)
          .where(and(
            eq(publishLogTable.postId, postId),
            eq(publishLogTable.platform, otherPlatform),
            eq(publishLogTable.status, "failed"),
          ));
        // If the other platform already failed, consider this post published (partial success)
        finalStatus = otherFailed ? "published" : "scheduled";
      }
    } else {
      // Esta plataforma falló — mantener "scheduled" para que la otra leg pueda correr.
      // Retry-first: si no se agotaron los intentos, reprogramar esta leg para reintento.
      finalStatus = "scheduled";
      isRetrying = currentRetries < MAX_PUBLISH_RETRIES - 1;
    }
  } else {
    if (anySuccess) {
      finalStatus = "published";
    } else if (currentRetries < MAX_PUBLISH_RETRIES - 1) {
      // Retry-first: slot permanece ocupado (status="scheduled") durante el reintento.
      finalStatus = "scheduled";
      isRetrying = true;
    } else {
      // Reintentos agotados — marcar failed y liberar el slot para nueva generación IA.
      finalStatus = "failed";
    }
  }

  const retryAt = isRetrying ? new Date(Date.now() + RETRY_DELAY_MS) : null;
  await db.update(postsTable).set({
    status: finalStatus,
    publishedAt: (anySuccess && finalStatus === "published") ? new Date() : undefined,
    publishRetries: isRetrying ? currentRetries + 1 : undefined,
    scheduledAt:          (isRetrying && retryAt && post.scheduledAt)                                        ? retryAt : undefined,
    scheduledAtInstagram: (isRetrying && retryAt && post.scheduledAtInstagram && platformOverride !== "tiktok")    ? retryAt : undefined,
    scheduledAtTiktok:    (isRetrying && retryAt && post.scheduledAtTiktok    && platformOverride !== "instagram") ? retryAt : undefined,
  }).where(eq(postsTable.id, postId));

  const logs = await db.select().from(publishLogTable).where(eq(publishLogTable.postId, postId));
  const latestLogs = logs.slice(-platforms.length);
  const successPls = latestLogs.filter(l => l.status === "published").map(l => l.platform);
  const failedPls  = latestLogs.filter(l => l.status === "failed").map(l => l.platform);

  if (anySuccess) {
    notifyPostPublished(postId, finalCaption ?? "", successPls, failedPls, post.userId ?? undefined).catch(e =>
      logger.warn(`Telegram publish notify failed: ${e}`)
    );
  } else if (isRetrying) {
    logger.warn({ postId, attempt: currentRetries + 1, maxRetries: MAX_PUBLISH_RETRIES },
      `[publishPost] Post #${postId} falló (intento ${currentRetries + 1}/${MAX_PUBLISH_RETRIES}) — reintento en ${RETRY_DELAY_MS / 60000} min`
    );
  } else {
    const firstFail = latestLogs.find(l => l.status === "failed");
    notifyPostFailed(
      postId,
      post.caption ?? "",
      firstFail?.platform ?? platforms[0],
      firstFail?.errorMessage ?? "Error desconocido",
      post.userId ?? undefined
    ).catch(e => logger.warn(`Telegram fail notify failed: ${e}`));
  }
}

const NICHE_INSIGHTS_INTERVAL_DAYS = 15;
const NICHE_INSIGHTS_LAST_RUN_KEY = "niche_insights_last_run";

/**
 * Core niche insights job: analyzes ER% per niche, asks GPT for suggestions,
 * sends Telegram report, and saves the run timestamp to app_settings.
 */
async function runNicheInsightsReport() {
  try {
    logger.info("[NicheInsights] Starting niche performance analysis...");
    const analysis = await analyzeAndSuggestNiches();
    logger.info(`[NicheInsights] Analysis done — ${analysis.allPerformance.length} niches with data, ${analysis.suggestions.length} suggestions generated.`);
    await notifyNicheInsights(analysis);
    // Persist run timestamp
    await db
      .insert(appSettingsTable)
      .values({ key: NICHE_INSIGHTS_LAST_RUN_KEY, value: new Date().toISOString() })
      .onConflictDoUpdate({ target: appSettingsTable.key, set: { value: new Date().toISOString() } });
    logger.info("[NicheInsights] Telegram report sent and timestamp saved.");
  } catch (err) {
    logger.error(`[NicheInsights] Report failed: ${err}`);
  }
}

/**
 * Daily gate: runs the niche insights report only if 15 calendar days have
 * elapsed since the last run (stored in app_settings as ISO string).
 * On first run (no stored date), it uses a default 14 days ago so the
 * first report fires tomorrow.
 */
async function maybeRunNicheInsightsReport() {
  try {
    const rows = await db.select().from(appSettingsTable).where(eq(appSettingsTable.key, NICHE_INSIGHTS_LAST_RUN_KEY));
    const lastRunStr = rows[0]?.value ?? null;

    let daysSinceLast: number;
    if (!lastRunStr) {
      // No record yet — initialize to 14 days ago so tomorrow is the first fire
      const initDate = new Date();
      initDate.setDate(initDate.getDate() - (NICHE_INSIGHTS_INTERVAL_DAYS - 1));
      await db
        .insert(appSettingsTable)
        .values({ key: NICHE_INSIGHTS_LAST_RUN_KEY, value: initDate.toISOString() })
        .onConflictDoUpdate({ target: appSettingsTable.key, set: { value: initDate.toISOString() } });
      logger.info(`[NicheInsights] First initialization — next report scheduled for tomorrow.`);
      return;
    }

    const lastRun = new Date(lastRunStr);
    const now = new Date();
    daysSinceLast = Math.floor((now.getTime() - lastRun.getTime()) / (1000 * 60 * 60 * 24));

    if (daysSinceLast >= NICHE_INSIGHTS_INTERVAL_DAYS) {
      logger.info(`[NicheInsights] ${daysSinceLast} days since last report — running now.`);
      await runNicheInsightsReport();
    } else {
      logger.info(`[NicheInsights] Only ${daysSinceLast} days since last report — next in ${NICHE_INSIGHTS_INTERVAL_DAYS - daysSinceLast} day(s).`);
    }
  } catch (err) {
    logger.error(`[NicheInsights] Daily gate check failed: ${err}`);
  }
}

/**
 * Daily at 01:00 Bogotá: downgrade any subscription whose periodEnd has passed.
 *
 * If the subscription has a `pendingDowngradePlan`, switch to that plan (queued
 * downgrade case — user requested it during their current cycle). Otherwise fall
 * back to "free" (subscription simply expired without renewal).
 */
async function expireSubscriptions() {
  try {
    const now = new Date();
    const expired = await db
      .select({
        id: subscriptionsTable.id,
        userId: subscriptionsTable.userId,
        plan: subscriptionsTable.plan,
        creditsTotal: subscriptionsTable.creditsTotal,
        pendingDowngradePlan: subscriptionsTable.pendingDowngradePlan,
        pendingDowngradeBusinessIds: subscriptionsTable.pendingDowngradeBusinessIds,
      })
      .from(subscriptionsTable)
      .where(
        and(
          lt(subscriptionsTable.periodEnd, now),
          eq(subscriptionsTable.status, "active")
        )
      );

    if (expired.length === 0) return;

    // Load plans once for credit-cap calculations
    const plans = await db.select().from(plansTable);

    for (const sub of expired) {
      const targetPlanKey = sub.pendingDowngradePlan ?? "free";
      const targetPlan = plans.find(p => p.key === targetPlanKey);
      const newCreditsTotal = targetPlan?.creditsPerMonth ?? 0;
      const isFree = targetPlanKey === "free";

      // Business rule: when a user downgrades to another paid plan (paid→paid),
      // the subscription remains ACTIVE — they are effectively renewing at a lower tier.
      // No additional payment check is performed here; the assumption is that the user
      // will renew their subscription separately. If this rule changes (e.g., require
      // payment confirmation before activating the lower paid tier), replace the
      // period advance logic below with a pending state until webhook confirmation.
      //
      // When going to free (no renewal), the subscription is marked EXPIRED.
      const nextStatus = isFree ? "expired" : "active";

      // Advance the billing period by 30 days for paid→paid downgrades so the
      // subscription is idempotently processed at most once per cycle.
      const newPeriodStart = isFree ? undefined : now;
      const newPeriodEnd = isFree ? undefined : new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

      // Snapshot plan capabilities at renewal time — locks in features for the new period
      const renewedPlanSnapshot = targetPlan ? buildPlanSnapshot(targetPlan) : null;

      await db.update(subscriptionsTable)
        .set({
          status: nextStatus,
          plan: targetPlanKey,
          creditsRemaining: newCreditsTotal,
          creditsTotal: newCreditsTotal,
          lockedPlanConfig: renewedPlanSnapshot,
          pendingDowngradePlan: null,
          pendingDowngradeAt: null,
          pendingDowngradeBusinessIds: [],
          ...(newPeriodStart ? { periodStart: newPeriodStart } : {}),
          ...(newPeriodEnd ? { periodEnd: newPeriodEnd } : {}),
          updatedAt: now,
        })
        .where(eq(subscriptionsTable.id, sub.id));
      await db.update(usersTable)
        .set({ plan: targetPlanKey, aiCredits: newCreditsTotal, updatedAt: now })
        .where(eq(usersTable.id, sub.userId));

      // Apply business inactivation when a queued downgrade is executed
      if (sub.pendingDowngradePlan) {
        const keepIds = Array.isArray(sub.pendingDowngradeBusinessIds) && sub.pendingDowngradeBusinessIds.length > 0
          ? (sub.pendingDowngradeBusinessIds as number[])
          : null;

        if (keepIds && keepIds.length > 0) {
          // Deactivate all businesses NOT in the keep list
          await db.update(businessesTable)
            .set({ isActive: false, isDefault: false, updatedAt: now })
            .where(and(
              eq(businessesTable.userId, sub.userId),
              eq(businessesTable.isActive, true),
              not(inArray(businessesTable.id, keepIds))
            ));

          // Reactivate any inactive businesses that the user explicitly selected to keep
          await db.update(businessesTable)
            .set({ isActive: true, updatedAt: now })
            .where(and(
              eq(businessesTable.userId, sub.userId),
              eq(businessesTable.isActive, false),
              inArray(businessesTable.id, keepIds)
            ));

          // Set the primary business (first in the list) as default
          const primaryId = keepIds[0];
          await db.update(businessesTable)
            .set({ isDefault: false })
            .where(and(eq(businessesTable.userId, sub.userId), eq(businessesTable.isActive, true)));
          await db.update(businessesTable)
            .set({ isDefault: true })
            .where(and(eq(businessesTable.id, primaryId), eq(businessesTable.userId, sub.userId)));

          logger.info(`[Subscriptions] Downgrade userId=${sub.userId}: kept businesses [${keepIds.join(", ")}], deactivated others, primary=${primaryId}`);
        }

        await auditLog({
          userId: sub.userId,
          action: AuditAction.DOWNGRADE_APPLIED,
          metadata: { fromPlan: sub.plan, toPlan: targetPlanKey, keepBusinessIds: keepIds ?? [], status: nextStatus },
        });
      }

      logger.info(
        `[Subscriptions] Cycle end userId=${sub.userId} — ${sub.plan} → ${targetPlanKey} (status=${nextStatus})` +
        (sub.pendingDowngradePlan ? " [queued downgrade applied]" : " [no renewal, expired]") +
        (newPeriodEnd ? ` [next period ends ${newPeriodEnd.toISOString().slice(0, 10)}]` : "")
      );
    }
  } catch (err) {
    logger.error(`[Subscriptions] Expiry check failed: ${err}`);
  }
}

/**
 * 1st of each month at 03:00 Bogotá:
 * Remove up to 10 tracks that are unprotected and never used (or unused for 30+ days),
 * then trigger a Pixabay sync to replenish the library.
 */
async function rotateMusicLibrary() {
  try {
    const cutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    const candidates = await db
      .select({ id: musicTracksTable.id })
      .from(musicTracksTable)
      .where(
        and(
          eq(musicTracksTable.isProtected, false),
          eq(musicTracksTable.usageCount, 0),
          or(
            sql`${musicTracksTable.lastUsedAt} IS NULL`,
            lte(musicTracksTable.lastUsedAt, cutoff)
          )
        )
      )
      .orderBy(musicTracksTable.addedAt)
      .limit(10);

    for (const { id } of candidates) {
      await db.delete(musicTracksTable).where(eq(musicTracksTable.id, id));
    }

    if (candidates.length > 0) {
      logger.info(`[Music] Rotación mensual: ${candidates.length} pistas eliminadas`);
    }

    if (process.env.PIXABAY_API_KEY && candidates.length > 0) {
      await syncMusicFromPixabay();
    }
  } catch (err) {
    logger.error(`[Music] Rotation failed: ${err}`);
  }
}


/**
 * On startup: seed built-in tracks, then optionally sync from Pixabay if key is available.
 */
async function syncMusicIfEmpty() {
  try {
    // Always seed built-in tracks (real SoundHelix MP3s, no synthesis)
    const { added } = await seedMusicLibrary();
    if (added > 0) logger.info(`[Music] ${added} pistas SoundHelix (CC BY-SA 4.0) agregadas`);
    else logger.info("[Music] Biblioteca de música ya inicializada");

    // Additionally sync from Pixabay if key is configured
    if (process.env.PIXABAY_API_KEY) {
      const [count] = await db
        .select({ total: sql<number>`count(*)` })
        .from(musicTracksTable)
        .where(and(
          eq(musicTracksTable.isValid, true),
          sql`${musicTracksTable.pixabayId} NOT LIKE 'sh:%'`,
          sql`${musicTracksTable.pixabayId} NOT LIKE 'fma:%'`
        ));
      if ((count?.total ?? 0) === 0) {
        logger.info("[Music] Sincronizando desde Pixabay...");
        await syncMusicFromPixabay();
      }
    }
  } catch (err) {
    logger.error(`[Music] Startup sync failed: ${err}`);
  }
}

/**
 * Fetch tracks from Pixabay and insert any new ones into the library.
 */
// ── Modern Pixabay sync queries — shared with routes/music.ts ─────────────────
const PIXABAY_SYNC_QUERIES = [
  { q: "electronic edm dance",        genre: "electrónica",  mood: "energético",    energyLevel: "high"   },
  { q: "synthwave retrowave",         genre: "electrónica",  mood: "moderno",       energyLevel: "high"   },
  { q: "trap beat hip hop urban",     genre: "trap",         mood: "urbano",        energyLevel: "high"   },
  { q: "hip hop modern beat",         genre: "trap",         mood: "energético",    energyLevel: "high"   },
  { q: "lofi hip hop chill",          genre: "lo-fi",        mood: "tranquilo",     energyLevel: "low"    },
  { q: "lofi beats study",            genre: "lo-fi",        mood: "relajado",      energyLevel: "low"    },
  { q: "phonk dark trap",             genre: "phonk",        mood: "dark",          energyLevel: "high"   },
  { q: "house music dance",           genre: "house",        mood: "festivo",       energyLevel: "high"   },
  { q: "deep house groove",           genre: "house",        mood: "energético",    energyLevel: "medium" },
  { q: "reggaeton latin urban",       genre: "latina",       mood: "festivo",       energyLevel: "high"   },
  { q: "latin pop tropical",          genre: "latina",       mood: "alegre",        energyLevel: "medium" },
  { q: "cinematic epic motivational", genre: "cinematic",    mood: "épico",         energyLevel: "medium" },
  { q: "inspirational corporate",     genre: "corporativa",  mood: "profesional",   energyLevel: "medium" },
  { q: "ambient relaxing calm",       genre: "ambient",      mood: "tranquilo",     energyLevel: "low"    },
];

async function syncMusicFromPixabay() {
  const apiKey = process.env.PIXABAY_API_KEY!;
  let added = 0;
  for (const { q, genre, mood, energyLevel } of PIXABAY_SYNC_QUERIES) {
    try {
      const url = `https://pixabay.com/api/?key=${apiKey}&media_type=music&q=${encodeURIComponent(q)}&per_page=5&order=popular`;
      const res = await fetch(url);
      const data = await res.json() as { hits?: Array<{ id: number; previewURL?: string; audioURL?: string; pageURL?: string; user?: string; duration?: number; tags?: string; bpm?: number }> };
      if (!data.hits) continue;
      for (const hit of data.hits) {
        const sourceUrl = hit.previewURL ?? hit.audioURL ?? "";
        if (!sourceUrl) continue;
        // Duration gate: 30–90s target range for social content
        const dur = hit.duration || 60;
        if (dur < 30 || dur > 90) continue;
        const pixId = String(hit.id);
        const existing = await db.select({ id: musicTracksTable.id }).from(musicTracksTable).where(eq(musicTracksTable.pixabayId, pixId)).limit(1);
        if (existing.length > 0) continue;
        const tags = (hit.tags || "").split(",").map((t: string) => t.trim()).filter(Boolean);
        const title = tags.slice(0, 3).map((t: string) => t.charAt(0).toUpperCase() + t.slice(1)).join(" · ") || `Track ${pixId}`;
        await db.insert(musicTracksTable).values({
          title, artist: hit.user || "Pixabay Artist", genre, mood,
          sourceUrl, pageUrl: hit.pageURL || "", duration: dur,
          bpm: hit.bpm || 0, tags: hit.tags || "", pixabayId: pixId,
          license: "Pixabay License", isValid: true, isProtected: false,
          energyLevel, isTrending: false,
        });
        added++;
      }
    } catch (err) {
      logger.error(`[Music] Pixabay query "${q}" failed: ${err}`);
    }
  }
  if (added > 0) logger.info(`[Music] Pixabay sync: ${added} pistas nuevas agregadas`);
}

const GRAPH_META = "https://graph.facebook.com/v20.0";

/**
 * Daily check: if any Meta (Instagram/Facebook) access token expires within 15 days,
 * attempt an automatic long-lived token renewal via fb_exchange_token.
 * Sends a Telegram alert on success, expiring-soon, or failure.
 */
export async function checkAndRenewMetaToken(): Promise<void> {
  try {
    const now = new Date();
    const threshold     = new Date(now.getTime() + 15 * 24 * 3600 * 1000);
    const fiftyDaysAgo  = new Date(now.getTime() - 50 * 24 * 3600 * 1000);

    // Fetch Instagram accounts that need renewal:
    //   1. Token expiry known AND expires within 15 days (standard case)
    //   2. Token expiry NULL AND last updated > 50 days ago (legacy accounts connected before
    //      token_expires_at was introduced — assumed to be at risk of expiry)
    const accounts = await db
      .select()
      .from(socialAccountsTable)
      .where(
        and(
          eq(socialAccountsTable.platform, "instagram"),
          or(
            and(
              isNotNull(socialAccountsTable.tokenExpiresAt),
              lte(socialAccountsTable.tokenExpiresAt, threshold),
            ),
            and(
              isNull(socialAccountsTable.tokenExpiresAt),
              lte(socialAccountsTable.updatedAt, fiftyDaysAgo),
            ),
          ),
        ),
      );

    if (accounts.length === 0) return;

    // Load Meta app credentials from app_settings
    const settingsRows = await db.select().from(appSettingsTable);
    const settings: Record<string, string> = Object.fromEntries(settingsRows.map(r => [r.key, r.value]));
    const appId     = settings["meta_app_id"];
    const appSecret = settings["meta_app_secret"];

    for (const account of accounts) {
      // For accounts without token_expires_at, treat them as already overdue (daysLeft = 0)
      const expiresAt = account.tokenExpiresAt ?? account.updatedAt ?? now;
      const daysLeft  = account.tokenExpiresAt
        ? Math.max(0, Math.floor((expiresAt.getTime() - now.getTime()) / 86_400_000))
        : 0;

      if (!appId || !appSecret) {
        logger.warn(`[MetaToken] meta_app_id/meta_app_secret not configured — skipping auto-renewal for user ${account.userId}`);
        await notifyMetaTokenAlert("expiring_soon", expiresAt, daysLeft, account.userId ?? undefined)
          .catch(e => logger.warn(`[MetaToken] Telegram alert failed: ${e}`));
        continue;
      }

      let currentToken: string;
      try {
        currentToken = decryptToken(account.accessToken);
      } catch {
        logger.error(`[MetaToken] Could not decrypt token for user ${account.userId}`);
        await notifyMetaTokenAlert("renewal_failed", expiresAt, daysLeft, account.userId ?? undefined)
          .catch(e => logger.warn(`[MetaToken] Telegram alert failed: ${e}`));
        continue;
      }

      // Try fb_exchange_token renewal
      const url = `${GRAPH_META}/oauth/access_token?grant_type=fb_exchange_token&client_id=${appId}&client_secret=${appSecret}&fb_exchange_token=${encodeURIComponent(currentToken)}`;
      const renewRes  = await fetch(url);
      const renewData = await renewRes.json() as { access_token?: string; expires_in?: number; error?: { message: string } };

      if (!renewData.access_token || renewData.error) {
        logger.error(`[MetaToken] Renewal failed for user ${account.userId}: ${renewData.error?.message ?? "no access_token"}`);
        await notifyMetaTokenAlert("renewal_failed", expiresAt, daysLeft, account.userId ?? undefined)
          .catch(e => logger.warn(`[MetaToken] Telegram alert failed: ${e}`));
        continue;
      }

      const newExpiresIn  = renewData.expires_in ?? 5_183_944; // ~60 days
      const newExpiresAt  = new Date(Date.now() + newExpiresIn * 1000);
      const encryptedNew  = encryptToken(renewData.access_token);
      const newDaysLeft   = Math.floor(newExpiresIn / 86_400);

      // Update both instagram + facebook accounts for this user
      await db
        .update(socialAccountsTable)
        .set({ accessToken: encryptedNew, tokenExpiresAt: newExpiresAt })
        .where(
          and(
            eq(socialAccountsTable.userId, account.userId!),
            or(
              eq(socialAccountsTable.platform, "instagram"),
              eq(socialAccountsTable.platform, "facebook"),
            ),
          ),
        );

      // Refresh ig_user_id using the new token — checks both instagram_business_account
      // and connected_instagram_account so Account Center-linked accounts are preserved.
      if (account.pageId) {
        try {
          const freshIgId = await resolveIgIdFromPageApi(account.pageId, renewData.access_token);
          await db
            .update(socialAccountsTable)
            .set({ igUserId: freshIgId })
            .where(eq(socialAccountsTable.id, account.id));
          logger.info(`[MetaToken] ig_user_id ${freshIgId ? `set: ${freshIgId}` : "cleared (no IG linked via Page Settings or Account Center)"} for account ${account.id} (user ${account.userId})`);
        } catch (e) {
          logger.warn(`[MetaToken] ig_user_id refresh failed for account ${account.id}: ${e}`);
        }
      }

      logger.info(`[MetaToken] Token renewed for user ${account.userId} — expires ${newExpiresAt.toISOString()} (${newDaysLeft} days)`);
      await notifyMetaTokenAlert("renewed", newExpiresAt, newDaysLeft, account.userId ?? undefined)
        .catch(e => logger.warn(`[MetaToken] Telegram alert failed: ${e}`));
    }
  } catch (err) {
    logger.error(`[MetaToken] checkAndRenewMetaToken crashed: ${err}`);
  }
}

/**
 * Sends monthly analytics summary emails to all active paid users.
 * Called on the 1st of each month at 10:00 Bogotá.
 */
export async function sendMonthlyAnalyticsEmails(): Promise<void> {
  const RESEND_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_KEY) {
    logger.warn("[MonthlyReport] RESEND_API_KEY not set — skipping monthly report emails");
    return;
  }

  const now = new Date();
  const prevMonthEnd   = new Date(now.getFullYear(), now.getMonth(), 0);
  const prevMonthStart = new Date(prevMonthEnd.getFullYear(), prevMonthEnd.getMonth(), 1);
  const periodStr = `${prevMonthStart.toLocaleDateString("es-CO", { day: "numeric", month: "short", year: "numeric" })} - ${prevMonthEnd.toLocaleDateString("es-CO", { day: "numeric", month: "short", year: "numeric" })}`;

  const paidUsers = await db
    .select({ id: usersTable.id, email: usersTable.email, displayName: usersTable.displayName, plan: usersTable.plan })
    .from(usersTable)
    .where(and(
      isNotNull(usersTable.email),
      sql`${usersTable.plan} != 'free'`,
    ));

  logger.info({ count: paidUsers.length, period: periodStr }, "[MonthlyReport] Sending monthly analytics emails");

  let sent = 0;
  let errors = 0;

  for (const user of paidUsers) {
    try {
      if (!user.email) continue;

      const [overview] = await db
        .select({
          total:     sql<number>`count(*)::int`,
          published: sql<number>`count(*) filter (where ${postsTable.status} = 'published')::int`,
          likes:     sql<number>`coalesce(sum(${postsTable.likes}), 0)::int`,
          reach:     sql<number>`coalesce(sum(${postsTable.reach}), 0)::int`,
          comments:  sql<number>`coalesce(sum(${postsTable.comments}), 0)::int`,
          saves:     sql<number>`coalesce(sum(${postsTable.saves}), 0)::int`,
        })
        .from(postsTable)
        .where(and(
          eq(postsTable.userId, user.id),
          gte(postsTable.publishedAt, prevMonthStart),
          lte(postsTable.publishedAt, prevMonthEnd),
        ));

      const bizName = user.displayName ?? "Tu negocio";
      const successRate = overview.total > 0 ? Math.round((overview.published / overview.total) * 100) : 0;
      const engScore = (overview.likes ?? 0) + (overview.saves ?? 0) * 2 + (overview.comments ?? 0);
      const er = (overview.reach ?? 0) > 0 ? (Math.round((engScore / overview.reach) * 1000) / 10).toFixed(1) : "0";
      const fmt = (n: number | null | undefined) => (n ?? 0).toLocaleString("es-CO");

      const html = `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Reporte mensual — ${bizName}</title></head>
<body style="margin:0;padding:0;background:#0f172a;font-family:'Segoe UI',Arial,sans-serif;color:#e2e8f0;">
  <div style="max-width:600px;margin:0 auto;padding:32px 16px;">
    <div style="background:linear-gradient(135deg,#00c253,#00c2ff);height:4px;border-radius:2px 2px 0 0;"></div>
    <div style="background:#1e293b;padding:32px;border-radius:0 0 12px 12px;">
      <div style="text-align:center;margin-bottom:24px;"><span style="font-size:28px;font-weight:900;color:#fff;">haz</span><span style="font-size:28px;font-weight:900;color:#00c2ff;">post</span></div>
      <h1 style="font-size:20px;font-weight:700;color:#f1f5f9;text-align:center;margin:0 0 4px 0;">Reporte Mensual de Analytics</h1>
      <p style="text-align:center;color:#94a3b8;font-size:14px;margin:0 0 24px 0;">${bizName} &mdash; ${periodStr}</p>
      <div style="background:#0f172a;border-radius:8px;padding:20px;margin-bottom:24px;">
        <table style="width:100%;border-collapse:collapse;">
          <tr style="border-bottom:1px solid #1e293b;"><td style="padding:9px 0;color:#94a3b8;font-size:13px;">Posts publicados</td><td style="padding:9px 0;text-align:right;color:#00c253;font-weight:700;">${fmt(overview.published)}</td></tr>
          <tr style="border-bottom:1px solid #1e293b;"><td style="padding:9px 0;color:#94a3b8;font-size:13px;">Tasa de éxito</td><td style="padding:9px 0;text-align:right;color:#f1f5f9;font-weight:600;">${successRate}%</td></tr>
          <tr style="border-bottom:1px solid #1e293b;"><td style="padding:9px 0;color:#94a3b8;font-size:13px;">Alcance total</td><td style="padding:9px 0;text-align:right;color:#00c2ff;font-weight:700;">${fmt(overview.reach)}</td></tr>
          <tr style="border-bottom:1px solid #1e293b;"><td style="padding:9px 0;color:#94a3b8;font-size:13px;">Likes totales</td><td style="padding:9px 0;text-align:right;color:#f472b6;font-weight:700;">${fmt(overview.likes)}</td></tr>
          <tr><td style="padding:9px 0;color:#94a3b8;font-size:13px;">Engagement Rate</td><td style="padding:9px 0;text-align:right;color:#a78bfa;font-weight:700;">${er}%</td></tr>
        </table>
      </div>
      <div style="text-align:center;margin-bottom:20px;"><a href="https://hazpost.app/analytics" style="display:inline-block;background:linear-gradient(135deg,#00c253,#00c2ff);color:#fff;font-weight:700;font-size:14px;padding:12px 28px;border-radius:8px;text-decoration:none;">Ver reporte completo →</a></div>
      <p style="color:#475569;font-size:11px;text-align:center;margin:0;">hazpost.app &mdash; IA para tus redes sociales</p>
    </div>
  </div>
</body></html>`;

      const resp = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": `Bearer ${RESEND_KEY}` },
        body: JSON.stringify({
          from: "HazPost <reportes@hazpost.app>",
          to: user.email,
          subject: `📊 Tu reporte mensual — ${bizName} (${periodStr})`,
          html,
        }),
      });

      if (resp.ok) {
        sent++;
      } else {
        const body = await resp.text();
        logger.warn({ userId: user.id, status: resp.status, body }, "[MonthlyReport] Resend rejected email");
        errors++;
      }
    } catch (err) {
      logger.error({ userId: user.id, err }, "[MonthlyReport] Failed to send monthly report");
      errors++;
    }
  }

  logger.info({ sent, errors, total: paidUsers.length }, "[MonthlyReport] Monthly analytics emails complete");
}

/**
 * Expose for manual trigger via API endpoint.
 */
export { runNicheInsightsReport };
