/**
 * Character limits for social media platforms.
 * SINGLE SOURCE OF TRUTH — see skill: .agents/skills/social-caption-limits/SKILL.md
 *
 * When a platform changes its limit, touch only two files:
 *   1. This file (backend) — update the relevant FULL + BODY constants.
 *   2. artifacts/social-dashboard/src/lib/socialLimits.ts (frontend mirror).
 *
 * ai.service.ts, instagram.service.ts, tiktok.service.ts, and approval.tsx
 * all read from these constants and need no changes.
 */

// ── Instagram ────────────────────────────────────────────────────────────────

/** Full Instagram caption limit (caption body + "\n\n" + hashtags combined) */
export const IG_CAPTION_LIMIT = 2200;

/**
 * Max length for the caption BODY generated by AI.
 * Leaves ~600 chars buffer for "\n\n" + hashtags within IG_CAPTION_LIMIT.
 */
export const IG_CAPTION_BODY_LIMIT = 1600;

// ── TikTok ───────────────────────────────────────────────────────────────────

/** Full TikTok caption limit (caption body + "\n\n" + hashtags combined) */
export const TIKTOK_CAPTION_LIMIT = 2200;

/**
 * Max length for the TikTok caption BODY generated by AI.
 * Leaves ~600 chars buffer for "\n\n" + hashtags within TIKTOK_CAPTION_LIMIT.
 */
export const TIKTOK_CAPTION_BODY_LIMIT = 1600;

// ── Facebook ─────────────────────────────────────────────────────────────────

/** Full Facebook caption limit (caption body + "\n\n" + hashtags combined) */
export const FB_CAPTION_LIMIT = 63206;

/**
 * Max length for the Facebook caption BODY generated by AI.
 * Facebook's technical limit is 63 206, but we cap at 1600 to keep
 * captions readable on mobile feeds.
 */
export const FB_CAPTION_BODY_LIMIT = 1600;

// ── Per-platform helper ───────────────────────────────────────────────────────

/**
 * Returns the correct caption BODY limit for a given platform.
 * Used by generateCaption and rethemeCaption — do not hardcode IG values.
 *
 * @param platform - "instagram" | "tiktok" | "facebook" | "both" (both → IG, most restrictive)
 */
export function getBodyLimitForPlatform(platform: string): number {
  switch (platform) {
    case "tiktok":    return TIKTOK_CAPTION_BODY_LIMIT;
    case "facebook":  return FB_CAPTION_BODY_LIMIT;
    case "instagram":
    case "both":
    default:          return IG_CAPTION_BODY_LIMIT;
  }
}
