// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tipografia/Duotono.tsx": () => import("../components/mockups/tipografia/Duotono.tsx"),
  "./components/mockups/tipografia/Editorial.tsx": () => import("../components/mockups/tipografia/Editorial.tsx"),
  "./components/mockups/tipografia/Titanio.tsx": () => import("../components/mockups/tipografia/Titanio.tsx")
};
